apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: 874454224631.dkr.ecr.us-east-1.amazonaws.com/app:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"  # Defina os limites de CPU conforme necessário
              memory: "256Mi"  # Defina os limites de memória conforme necessário
            requests:
              cpu: "0.25"  # Defina as solicitações de CPU conforme necessário
              memory: "256Mi"  # Defina as solicitações de memória conforme necessário
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
spec:
  rules:
    - host: app-lanchonete.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: app
                port:
                  number: 80
